version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PIP3_INSTALL: "pip3 install --no-cache-dir -i https://pypi.tuna.tsinghua.edu.cn/simple/ "
    image: web:v1
    ports:
      - "8000:8000"
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
    volumes:
      - ./run:/app/run