version: '3.7'

services:
  rerank:
    build:
      context: .
      dockerfile: Dockerfile
    image: rerank:v1
    container_name: rerank-container
    ports:
      - "8022:8000"
    volumes:
      - ./logs:/app/logs
      - ./run:/app/run
      - /data/models:/data/models
    environment:
      CUDA_VISIBLE_DEVICES: 1
      MODEL_NAME: bge-reranker-base
      MAX_LENGTH: 512
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail localhost:8000/health | grep -q 'ok' || exit 1" ]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 3s
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 2
              capabilities: [gpu]        

